# Combined GCB (cloudbuild) config
#
# Setup: Create one or more triggers in GCB. Both branch and tags are supported.
#
# Commit builds (branch push):
#
#   - Builds and tags: commit-{SHORT_SHA}, latest
#
# Tag builds (version tag push matching vX.Y.Z):
#
# - Checks if `commit-SHA` image exists
#   - If yes, retags existing image in GCR
#   - Otherwise, builds from scratch
# - Creates the tags: $TAG_NAME, stable, commit-$SHORT_SHA

steps:
  - id: Check-Prebuilt-Image
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set +e
        if [[ -n "$TAG_NAME" && "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          echo "Build type: TAG $TAG_NAME"
          echo
          echo "Checking image: gcr.io/$PROJECT_ID/zag:commit-$SHORT_SHA"

          if gcloud container images describe "gcr.io/$PROJECT_ID/zag:commit-$SHORT_SHA" 2>&1; then
            echo "Found existing image; will not build from scratch"
            gcloud container images add-tag "gcr.io/$PROJECT_ID/zag:commit-$SHORT_SHA" \
              "gcr.io/$PROJECT_ID/zag:$TAG_NAME" \
              "gcr.io/$PROJECT_ID/zag:stable"
            echo "NEEDS_NEW_BUILD=false" > /workspace/build_status
            exit 0
          fi

          echo "Image not found, will build from scratch"
          echo "NEEDS_NEW_BUILD=true" > /workspace/build_status
          exit 0
        fi

        echo "Build type: COMMIT $SHORT_SHA"
        echo "Forced to build new image"
        echo "NEEDS_NEW_BUILD=true" > /workspace/build_status

  - id: Conditional-Build
    name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        source /workspace/build_status
        if [ "$$NEEDS_NEW_BUILD" != "true" ]; then
          exit 0
        fi

        echo "Setting up buildx for inline cache"
        docker buildx create --use --driver docker-container --name zag-builder || docker buildx use zag-builder

        echo "Rebuilding image with inline cache"
        docker buildx build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --build-arg PROJECT_ID=$PROJECT_ID \
          --cache-from gcr.io/$PROJECT_ID/zag:latest \
          --label org.opencontainers.image.source=https://github.com/ripta/zag \
          --label org.opencontainers.image.revision=$COMMIT_SHA \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t gcr.io/$PROJECT_ID/zag:commit-$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/zag:latest \
          .

        echo "Image pushed: gcr.io/$PROJECT_ID/zag:commit-$SHORT_SHA"
        echo "Image pushed: gcr.io/$PROJECT_ID/zag:latest"

options:
  dynamicSubstitutions: true
